//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChooseHealthy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ProviderTypes { get; set; }
        public int Distance { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
    }
}
